const STATUS_CODES = {
  INTERNAL_SERVER_ERROR: 500,
  SUCCESS: 200,
  BAD_REQUEST: 400,
};

const ERROR_MESSAGES = {
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  SUCCESS: "Ok",
};

module.exports = { STATUS_CODES, ERROR_MESSAGES };
